'use strict';

export const SAVE_PLAYER1_ACTION = 'SAVE_PLAYER1_ACTION';
export const SAVE_PLAYER2_ACTION = 'SAVE_PLAYER2_ACTION';
export const SAVE_PLAYER1_SCORE_ACTION = 'SAVE_PLAYER1_SCORE_ACTION';
export const SAVE_PLAYER2_SCORE_ACTION = 'SAVE_PLAYER2_SCORE_ACTION';
